### ISSUE TITLE
`appName` that contains a `-` lead to an error in proto file

### ISSUE THREAD

**Issue by brumhard** [SchwarzIT/go-template#97]
### What happened?

```shell
❯ make generate           
PATH=/private/tmp/awesome-project/bin:$PATH buf generate
api/proto/awesome-project/v1/awesome-project.proto:3:17:syntax error: unexpected '-', expecting ';'
make: *** [generate] Error 100
```

### How can we reproduce this?

Create a new project using the following file (`gt new -c values.yaml`):
```yaml
# values.yaml
base:
  projectName: Testing Project
  projectSlug: testing-project
  projectDescription: Some project used for testing
  appName: testing-project
  moduleName: github.com/fake/testing
  golangciVersion: 1.42.1
extensions:
  grpc:
    base: true
```

Then run `make generate`.

### gt version

```bash
0.3.0
```

### Search

- [X] I did search for other open and closed issues before opening this.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Additional context

Probably the issue is the newly added support for dashes in appNames which are not allowed in protobuf.
